"""
exporter.py — SEBI SME IPO Export Bundle Generator
===================================================================
Packages the Draft Abridged Prospectus DOCX (generated by generator.py, the
same module /api/generate uses) together with the audit log, coverage report,
and contradiction findings into a ZIP bundle, with a blockchain anchor of the
bundle's hash.
"""

import json
import os
import tempfile
import zipfile
import logging
from io import BytesIO
from datetime import datetime, timezone
from typing import Dict, Any

logger = logging.getLogger("sebi-ipo-generator.exporter")


def create_export_zip_bundle(session_data: Dict[str, Any], user_id: str = "default_user") -> bytes:
    """Packages the Draft Abridged Prospectus DOCX, Audit Log, Coverage Report, and Contradiction Findings into a ZIP bundle."""
    from generator import generate_draft_docx
    from coverage import compute_coverage
    from validator import validate_session_data
    from audit_log import AuditLog
    from blockchain import anchor_document_hash

    form_data = session_data.get("form_data", session_data)
    company_name = form_data.get("company_name", "Sunrise_Ceramics")
    safe_company = "".join(c if c.isalnum() else "_" for c in company_name)
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")

    schema_path = os.path.join(os.path.dirname(__file__), "schema.json")
    with open(schema_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    # 1. Generate the Draft Abridged Prospectus DOCX — reuses generator.py's
    # generate_draft_docx (the same real, DOCX-XML-formatted generator /api/generate
    # uses), instead of this file's own former generate_sebi_drhp_docx /
    # generate_abridged_prospectus_docx stubs. Those read field names that don't
    # exist anywhere in the current schema (issue_size_cr, revenue_fy24,
    # gcp_amount_cr, existing_shares_cr, ...) and silently fell back to hardcoded
    # placeholder numbers, so every exported bundle shipped a generic, wrong
    # document instead of the real one the Wizard/Dashboard actually produces.
    # There has only ever been one real generator (the Abridged Prospectus) —
    # the "DRHP" stub was never a distinct, working document.
    fd, tmp_path = tempfile.mkstemp(suffix=".docx")
    os.close(fd)
    try:
        generate_draft_docx(session_data, schema, tmp_path)
        with open(tmp_path, "rb") as f:
            draft_bytes = f.read()
    finally:
        os.remove(tmp_path)

    # 2. Coverage & Contradiction Reports
    # Reuses validate_session_data (the same engine that powers the live Dashboard's
    # conflict list) rather than the old ContradictionDetector class, which checked
    # for field names (issue_size_cr, gcp_amount_cr, promoter_holding_pct, ...) that
    # don't exist anywhere in the current schema — it always silently returned zero
    # findings, so every exported bundle claimed a clean contradiction report even
    # when the Dashboard was actively showing real conflicts to the user.
    coverage_report = compute_coverage(session_data).model_dump(mode="json")
    contradictions = validate_session_data(session_data, schema).get("inconsistencies", [])

    # 3. Audit Log
    logger_inst = AuditLog()
    audit_entries = [a.model_dump(mode="json") for a in logger_inst.get_log(user_id, limit=500)]

    # 4. Zip compilation
    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zipf:
        zipf.writestr(f"{safe_company}_Draft_Abridged_Prospectus_{date_str}.docx", draft_bytes)
        zipf.writestr("coverage_report.json", json.dumps(coverage_report, indent=2))
        zipf.writestr("contradiction_findings.json", json.dumps(contradictions, indent=2))
        zipf.writestr("audit_log.jsonl", "\n".join(json.dumps(e) for e in audit_entries))

    bundle_bytes = zip_buffer.getvalue()

    # Anchor ZIP Hash on Polygon Blockchain
    try:
        anchor_document_hash(bundle_bytes, doc_type="ZIP_EXPORT_BUNDLE")
        logger_inst.log(user_id=user_id, action="blockchain.anchor", resource="export_zip", outcome="success")
    except Exception as e:
        logger.warning(f"Blockchain anchoring for ZIP export skipped: {e}")

    logger_inst.log(user_id=user_id, action="export.docx", resource=f"{safe_company}_Export_Bundle_{date_str}.zip", outcome="success")

    return bundle_bytes


def create_efiling_package_zip(session_data: Dict[str, Any], output_path: str) -> str:
    """Legacy compatibility helper to write e-filing ZIP package to a target file path."""
    bundle_bytes = create_export_zip_bundle(session_data)
    with open(output_path, "wb") as f:
        f.write(bundle_bytes)
    return output_path
